# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Arnaud' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Arnaud
  pod 'Alamofire'

  target 'ArnaudTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
